FROM almalinux:8
## RUN cd /tmp ## cd not works ##
WORKDIR /tmp
RUN echo "HELLO WORLD" > sunny.txt
## WORKDIR /tmp means if we enter into container direct enter into /tmp directory
## Workdir insturation it will site the corrent working directory ##