ARG version
FROM almalinux:${version}
RUN echo "version passed by user is: ${version}"


## for example: we are creating image that is almalinux version 8 after version 9 we need to use version 9 then without changing image to use ARG instruatin to change version to same image ## 