FROM nginx
RUN rm -rf /usr/share/nginx/html/index.html     ## removing default html file
COPY index.html /usr/share/nginx/html/index.html  ## files should be avaviable in currnet directory, when dockerfile exist